DROP TABLE IF EXISTS AIRPORT_CODE;
 
CREATE TABLE AIRPORT_CODE(
  id INT AUTO_INCREMENT PRIMARY KEY,
  airport_code VARCHAR(250) NOT NULL,
  city VARCHAR(250) NOT NULL,
  country VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS FLIGHT_NUMBER_INVENTORY;
 
CREATE TABLE FLIGHT_NUMBER_INVENTORY(
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  flight_number VARCHAR(250) NOT NULL,
  airport_code VARCHAR(250) NULL,
  avaialable_date_from DATE NULL,
  avaialable_date_to DATE  NULL
);

DROP TABLE IF EXISTS FLIGHT_TARIFF;
 
CREATE TABLE FLIGHT_TARIFF(
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  flight_number VARCHAR(250) NOT NULL,
  flight_tariff double default '0',
  effective_date_from DATE NULL,
  effective_date_to DATE  NULL
 );